# Generated by Django 4.2.7 on 2025-06-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_ticketcategory_max_tickets_per_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='initial_tickets',
            field=models.PositiveIntegerField(blank=True, help_text='Initial number of tickets in this category', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='available_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='available_tickets',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Current number of tickets available', null=True),
        ),
    ]
