# Generated by Django 4.2.7 on 2025-06-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_ticketcategory_initial_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategory',
            name='available_tickets',
            field=models.PositiveIntegerField(default=0, help_text='Current number of tickets available'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='initial_tickets',
            field=models.PositiveIntegerField(default=0, help_text='Initial number of tickets in this category'),
        ),
    ]
