# Generated by Django 4.2.7 on 2025-07-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_ticketcategory_available_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
