# Generated by Django 4.2.7 on 2025-06-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_ticket_price_ticket_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategory',
            name='max_tickets_per_purchase',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of tickets one person can buy'),
        ),
    ]
