# Generated by Django 4.2.7 on 2025-08-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_ticket_buyer_ticket_cancelled_at_ticket_status_and_more'),
        ('events', '0007_ticket_transaction_code'),
    ]

    operations = [
    ]
