# Generated by Django 5.1 on 2026-01-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller_merchandise", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellermerchandise",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sellermerchandisecategory",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sellermerchandiseorder",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sellerorderitem",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
