# Generated by Django 4.2.7 on 2025-07-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='checkout_request_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='merchant_request_id',
        ),
    ]
